version: '3.8'

services:
  # Backend API Service (Development)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: habit-tracker-backend-dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/habit-tracker
      - JWT_SECRET=${JWT_SECRET:-dev_jwt_secret_key}
      - EMAIL_USER=${EMAIL_USER:-your_email@gmail.com}
      - EMAIL_PASS=${EMAIL_PASS:-your_email_password}
      - PORT=5000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
    networks:
      - habit-tracker-network

  # Frontend React Service (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: habit-tracker-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - habit-tracker-network

  # MongoDB Database Service
  mongo:
    image: mongo:7.0
    container_name: habit-tracker-mongo-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=habit-tracker
    volumes:
      - mongo_dev_data:/data/db
    restart: unless-stopped
    networks:
      - habit-tracker-network

  # MongoDB Admin Interface
  mongo-express:
    image: mongo-express:latest
    container_name: habit-tracker-mongo-express-dev
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - habit-tracker-network

volumes:
  mongo_dev_data:
    driver: local

networks:
  habit-tracker-network:
    driver: bridge
